repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.6"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
